# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 056619f380c0f34870293ee569c27877bd847a8584a5ab71604aada4d87a9e880a004b939ddb79ff91e93c6ae998fdbd8c9463a7f78ed0bdad419967e5f4ba8a

test:
  secret_key_base: d28cf67eef5493175d88fd0ff4b8abbeb517cc93170a48ac9dd0fc625a0b12d4f99ad58ef46a3e76af3a755609daa45fa736d4d3c167f474774fc42c9a401394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
